// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5BhdQPfM31xLaI4XkyUvKcgiAYg5PWUo',
    appId: '1:1030051779250:web:d6eb6eb68849dd7c0dafab',
    messagingSenderId: '1030051779250',
    projectId: 'flutter-app-bf05e',
    authDomain: 'flutter-app-bf05e.firebaseapp.com',
    storageBucket: 'flutter-app-bf05e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_XdW42M0kh_L0H3LfS7xybv5tyaUUuhs',
    appId: '1:1030051779250:android:6a5da8ba4ca2706d0dafab',
    messagingSenderId: '1030051779250',
    projectId: 'flutter-app-bf05e',
    storageBucket: 'flutter-app-bf05e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSQ4wapGYjkXGIJWCTe3yHjcU36XEzWDg',
    appId: '1:1030051779250:ios:ea53228fdb963f8a0dafab',
    messagingSenderId: '1030051779250',
    projectId: 'flutter-app-bf05e',
    storageBucket: 'flutter-app-bf05e.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSQ4wapGYjkXGIJWCTe3yHjcU36XEzWDg',
    appId: '1:1030051779250:ios:b7ae990db3875b290dafab',
    messagingSenderId: '1030051779250',
    projectId: 'flutter-app-bf05e',
    storageBucket: 'flutter-app-bf05e.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
